apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: canary-demo
  labels:
    app: canary-demo
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: canary-demo
