apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-demo
  labels:
    app: canary-demo
spec:
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
        - name: container
          image: canary-demo:1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128M"
